services:
    postgres_api_money_manager:
        image: postgres
        container_name: postgres_api_money_manager
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres_api_money_manager:/var/lib/postgresql
        networks:
            - network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    postgres_api_money_manager:
        driver: local
