services:
    postgres_api_money_manager:
        image: postgres
        container_name: postgres_api_money_manager
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres_api_money_manager:/var/lib/postgresql
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    postgres_api_money_manager:
        driver: local
